# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAL6fYhpo-XHvwTRJWS8_0vWNjIrkU0y
"""

# ===============================================================
# 🧠 PERBANDINGAN 3 VARIAN NAIVE BAYES PADA DATASET DIABETES (Streamlit)
# ===============================================================

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Judul Aplikasi
st.title("🧠 Perbandingan 3 Varian Naive Bayes pada Dataset Diabetes")
st.markdown("Dibuat dengan ❤️ menggunakan **Streamlit** & **scikit-learn**")

# Upload Dataset
uploaded_file = st.file_uploader("📂 Upload file CSV (contoh: diabetes.csv)", type=["csv"])

if uploaded_file:
    # 2️⃣ Load Dataset
    data = pd.read_csv(uploaded_file)
    st.subheader("📊 Data Awal")
    st.dataframe(data.head())
    st.write("Jumlah data:", data.shape)

    # 3️⃣ Pisahkan Fitur dan Label
    X = data.drop('Outcome', axis=1)
    y = data['Outcome']

    # 4️⃣ Split Data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 5️⃣ Daftar Model
    models = {
        "GaussianNB": GaussianNB(),
        "MultinomialNB": MultinomialNB(),
        "BernoulliNB": BernoulliNB()
    }

    # 6️⃣ Loop Model
    results = {}
    for name, model in models.items():
        X_train_mod = X_train.copy()
        X_test_mod = X_test.copy()
        if name != "GaussianNB":
            X_train_mod = X_train_mod - X_train_mod.min()
            X_test_mod = X_test_mod - X_test_mod.min()

        model.fit(X_train_mod, y_train)
        y_pred = model.predict(X_test_mod)

        acc = accuracy_score(y_test, y_pred)
        report = classification_report(y_test, y_pred, output_dict=True)
        cm = confusion_matrix(y_test, y_pred)

        results[name] = {
            "accuracy": acc,
            "precision_0": report["0"]["precision"],
            "recall_0": report["0"]["recall"],
            "f1_0": report["0"]["f1-score"],
            "precision_1": report["1"]["precision"],
            "recall_1": report["1"]["recall"],
            "f1_1": report["1"]["f1-score"],
            "confusion_matrix": cm
        }

        st.markdown(f"### 🔹 {name}")
        st.write(f"**Accuracy:** {acc:.4f}")
        st.text(classification_report(y_test, y_pred))

        # Confusion Matrix
        fig, ax = plt.subplots()
        sns.heatmap(cm, annot=True, fmt='d', cmap='YlGnBu', ax=ax)
        ax.set_title(f"{name} - Confusion Matrix")
        st.pyplot(fig)

    # 7️⃣ Ringkasan Metrik
    df_summary = pd.DataFrame(results).T[
        ["accuracy", "precision_0", "recall_0", "f1_0", "precision_1", "recall_1", "f1_1"]
    ]
    st.subheader("📋 Ringkasan Hasil Metrik Setiap Model")
    st.dataframe(df_summary.round(3))

    # 8️⃣ Visualisasi Akurasi
    st.subheader("📈 Perbandingan Akurasi Antar Model")
    fig, ax = plt.subplots()
    sns.barplot(x=df_summary.index, y=df_summary["accuracy"], palette="viridis", ax=ax)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Model")
    ax.set_ylabel("Accuracy")
    ax.set_title("Perbandingan Akurasi Antar Model Naive Bayes")
    st.pyplot(fig)

else:
    st.info("⬆️ Silakan upload file `diabetes.csv` terlebih dahulu.")